name: Build and Push Docker Image

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      docker_tag:
        type: choice
        description: 'Docker Image Tag'
        default: 'test'
        options:
          - test
          - dev

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: docker build --tag pocket-moodle-api:${{ github.event.inputs.docker_tag || github.event_name == 'release' && 'latest' }} .

      - name: Save Docker layers cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}

      - name: Deploy
        run: |
          cd /home/aitusa/server_side_configs/
          git pull
          ./reload_pm.sh

      - name: Send Telegram Notify To IT Chat
        if: github.event_name != 'release'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_IT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} builded and deployed Pocket Moodle API ${{ github.event.inputs.docker_tag }}:

            https://github.com/${{github.repository}}/commit/${{github.sha}}/checks/${{github.run_id}}
